#!/usr/bin/env php
<?php

require __DIR__.'/../../vendor/autoload.php';

use IQ2i\DataImporter\Tests\fixtures\Command\BookImportCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new BookImportCommand());
$application->run();
